PageRating/src/objects/Record_Page__c.object
<CustomObject>
    <fields>
        <fullName>Overall_Rating__c</fullName>
        <formula>IF( Total_Number_Of_Ratings__c = 0, 0,  Sum_Of_Ratings__c / Total_Number_Of_Ratings__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overall Rating</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_Developer_Name__c</fullName>
        <label>Page Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Object_Name__c</fullName>
        <label>Related Object Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Number_Of_Ratings__c</fullName>
        <label>Total Number of Ratings</label>
        <summaryForeignKey>Record_Page_Rating__c.Page_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Record Page</label>
    <nameField>
        <label>Page Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PageRating/src/objects/Record_Page_Rating__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <referenceTo>Record_Page__c</referenceTo>
        <relationshipLabel>Ratings</relationshipLabel>
        <relationshipName>Record_Page_Rating</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Rating</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Record Page Rating</label>
    <nameField>
        <displayFormat>RTG-{00000}</displayFormat>
        <label>Rating #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Page Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PageRating/src/classes/RecordPageRatingController.cls
public class RecordPageRatingController {

    @AuraEnabled
    public static String getOverallRating(String pageName, Id recordId){
        String retVal;
        
        if (String.IsBlank(pageName)){
            return JSON.serialize(getError('Page Name cannot be blank'));
        } 
        if (recordId == null){
            return JSON.serialize(getError('Record ID cannot be blank'));
        } 
        
        String objectName = recordId.getSobjectType().getDescribe().getName();
        
        List<Record_Page__c> recordPages = [SELECT Id, Overall_Rating__c
                                                 , Total_Number_Of_Ratings__c
                                                 , Related_Object_Name__c
                                              FROM Record_Page__c
                                             WHERE Page_Developer_Name__c = :pageName];
        
        if (recordPages.size() == 0){
            return JSON.serialize(getError('Unable to find details for this record page'));
        }
        if (recordPages.size() == 1 && recordPages.get(0).Related_Object_Name__c != objectName){
            return JSON.serialize(getError('The page you selected is not related to object ' + objectName));
        }
        
        PageOverallRating pageRating = new PageOverallRating();
        pageRating.recordPageId = recordPages.get(0).Id;
        pageRating.overallRating = recordPages.get(0).Overall_Rating__c;
        pageRating.totalRatings = (Integer)recordPages.get(0).Total_Number_Of_Ratings__c;
        pageRating.returnStatus = 'SUCCESS';
        
        return JSON.serialize(pageRating);
    }
    
    @AuraEnabled
    public static String addNewRating(Id recordPageId, String rating, String comments){
        try{
            Record_Page_Rating__c newRating = new Record_Page_Rating__c();
            newRating.Page_Name__c = recordPageId;
            newRating.Rating__c = Integer.valueOf(rating);
            newRating.Comments__c = comments;
            insert newRating;
            
            return JSON.serialize(new ReturnValue('SUCCESS'));
        }
        catch(Exception e){
            return JSON.serialize(getError(e.getMessage()));
        }
    }
    
    public virtual class ReturnValue{
        public String returnStatus;
        public ReturnValue(){
            returnStatus = '';
        }
        public ReturnValue(String status){
            returnStatus = status;
        }
    }
    
    public class PageOverallRating extends ReturnValue{
        public Id recordPageId;
        public Decimal overallRating;
        public Integer totalRatings;
    }

    public class Error extends ReturnValue{
        public String errorMessage;
    }
    
    private static Error getError(String errMsg){
        Error err = new Error();
        err.returnStatus = 'ERROR';
        err.errorMessage = errMsg;
        return err;
    }
    
}